theme = "kanagaway"

[editor]
mouse                     = false
cursorline                = true
auto-format               = true
auto-completion           = false
continue-comments         = false
middle-click-paste        = false
preview-completion-insert = false

[editor.gutters]
layout = [ "diff", "spacer", "diagnostics", "spacer", "spacer" ]

[editor.lsp]
auto-signature-help         = false
display-signature-help-docs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-pairs]
"`"  = "`"
"'"  = "'"
"\"" = "\""
"("  = ")"
"["  = "]"
"{"  = "}"

[keys.normal]
c = "toggle_comments"
L = "goto_line_end"
H = "goto_first_nonwhitespace"
J = [ "page_cursor_half_down", "align_view_center" ]
K = [ "page_cursor_half_up", "align_view_center" ]
tab = "no_op"
"]" = [ "goto_next_diag", "align_view_center" ]
"[" = [ "goto_prev_diag", "align_view_center" ]
esc = ["collapse_selection", "keep_primary_selection"]
"C-u" = "@miw<A-`>;"

[keys.normal.space]
l   = { d = ":set inline-diagnostics.cursor-line disable", h = ":set inline-diagnostics.cursor-line hint", w = ":set inline-diagnostics.cursor-line warning", e = ":set inline-diagnostics.cursor-line error" }
e   = "file_explorer_in_current_buffer_directory"
E   = "file_explorer"

[keys.normal.g]
j = [ ":new", ":insert-output yazi", ":buffer-close!", ":redraw" ]
k = [ ":new", ":insert-output lazygit", ":buffer-close!", ":redraw" ]

[keys.select]
c = "toggle_comments"
H = "goto_first_nonwhitespace"
L = "goto_line_end"

[keys.insert]
"C-space" = "completion"
"C-s"     = "signature_help"
"C-u"     = "@<esc>hmiw<A-`>;li"
up        = "no_op"
down      = "no_op"
left      = "no_op"
right     = "no_op"
pageup    = "no_op"
pagedown  = "no_op"
home      = "no_op"
end       = "no_op"
