theme = "kanagaway"

[editor]
mouse                     = false
cursorline                = true
auto-format               = true
auto-completion           = false
continue-comments         = false
middle-click-paste        = false
preview-completion-insert = false
[editor.gutters]
layout = [ "diff", "diagnostics", "spacer", "spacer", "spacer", "spacer" ]

[editor.lsp]
auto-signature-help         = false
display-color-swatches      = false
display-signature-help-docs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-pairs]
"`"  = "`"
"'"  = "'"
"\"" = "\""
"("  = ")"
"["  = "]"
"{"  = "}"

[keys.normal]
c = "toggle_comments"
L = "goto_line_end"
H = "goto_first_nonwhitespace"
J = [ "page_cursor_half_down", "align_view_center" ]
K = [ "page_cursor_half_up", "align_view_center" ]
tab = "no_op"
"]" = [ "goto_next_diag", "align_view_center" ]
"[" = [ "goto_prev_diag", "align_view_center" ]
esc = ["collapse_selection", "keep_primary_selection"]
"C-u" = "@miw<A-`>;"

[keys.normal.space]
e   = "file_explorer_in_current_buffer_directory"
E   = "file_explorer"

[keys.normal.space.l]
d = ":set inline-diagnostics.cursor-line disable"
h = ":set inline-diagnostics.cursor-line hint"
w = ":set inline-diagnostics.cursor-line warning"
e = ":set inline-diagnostics.cursor-line error"

[keys.normal.t]
u     = ":pipe lua ~/.config/helix/scripts/capitalize.lua"
s     = ":pipe lua ~/.config/helix/scripts/case_to_snake.lua"
c     = ":pipe lua ~/.config/helix/scripts/case_to_camel.lua"
p     = ":pipe lua ~/.config/helix/scripts/case_to_pascal.lua"
space = ":pipe lua ~/.config/helix/scripts/case_to_space.lua"

[keys.normal.t.r]
space = ":pipe lua ~/.config/helix/scripts/rm_spaces.lua"
_     = ":pipe lua ~/.config/helix/scripts/rm_underscore.lua"
-     = ":pipe lua ~/.config/helix/scripts/rm_hyphens.lua"

[keys.normal.g]
# l = [ ":new", ":insert-output lazygit", ":bc!", ":redraw" ]
y = "@:insert-output ~/.config/helix/scripts/yazi.fish ./%[buffer_name]<ret>_\"aduu:o <C-r>a<ret>:redraw<ret>"
Y = "@:insert-output ~/.config/helix/scripts/yazi.fish<ret>_\"aduu:o <C-r>a<ret>:redraw<ret>"

[keys.select]
c = "toggle_comments"
H = "goto_first_nonwhitespace"
L = "goto_line_end"

# [keys.select.f]
# h = "@:pipe superhtml fmt --stdin<ret><esc>"

[keys.select.t]
u     = ":pipe lua ~/.config/helix/scripts/capitalize.lua"
s     = ":pipe lua ~/.config/helix/scripts/case_to_snake.lua"
c     = ":pipe lua ~/.config/helix/scripts/case_to_camel.lua"
p     = ":pipe lua ~/.config/helix/scripts/case_to_pascal.lua"
space = ":pipe lua ~/.config/helix/scripts/case_to_space.lua"

[keys.select.t.r]
space = ":pipe lua ~/.config/helix/scripts/rm_spaces.lua"
_     = ":pipe lua ~/.config/helix/scripts/rm_underscore.lua"
-     = ":pipe lua ~/.config/helix/scripts/rm_hyphens.lua"

[keys.insert]
"C-space" = "completion"
"C-s"     = "signature_help"
"C-u"     = "@<esc>hmiw<A-`>;li"
"C-p"     = "@<esc>hmiw<A-`>;li"
up        = "no_op"
down      = "no_op"
left      = "no_op"
right     = "no_op"
pageup    = "no_op"
pagedown  = "no_op"
home      = "no_op"
end       = "no_op"
